/**
 * CQP Linter — adds a "Check Code Quality" button to CodeRunner questions.
 *
 * Sends student code to the Moodle web service which forwards it to the Jobe
 * sandbox for pylint/pycodestyle/custom analysis, then renders violations
 * inline in the Ace editor and in a results panel below the answer box.
 *
 * Also records lint events when students interact with CodeRunner's own
 * Check and Precheck buttons, capturing the last known lint state at that
 * moment so the researcher can correlate code-quality awareness with testing
 * behaviour across the three button types:
 *   cqp      – student clicked our "Check Code Quality" button
 *   check    – student clicked CodeRunner's "Check" (test-run) button
 *   precheck – student clicked CodeRunner's "Precheck" button
 *   submit   – quiz submitted (written server-side by the observer)
 *
 * @module     local_coderunner_cqp_linter/cqp_linter
 * @copyright  2026 Your Name
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
define(['core/ajax'], function(Ajax) {
    'use strict';

    /** CSS class prefix for CQP severity highlighting in the Ace editor. */
    var HIGHLIGHT_CLASSES = {
        fatal:      'cqp-highlight-error',
        error:      'cqp-highlight-error',
        warning:    'cqp-highlight-warning',
        refactor:   'cqp-highlight-refactor',
        convention: 'cqp-highlight-convention',
        info:       'cqp-highlight-info'
    };

    /** User-facing strings for the AI feedback section. */
    var STR = {
        aiTitle:      'AI Feedback (experimental)',
        aiSource:     'AI',
        aiLoading:    'Analysing code with AI…',
        aiDisclaimer: 'This feedback is generated by an AI model and may be incomplete or incorrect. ' +
                      'Treat it as suggestions, not a definitive grade.',
        aiError:      'AI analysis is unavailable right now.',
        aiClean:      'The AI found no issues for the assessed principles.'
    };

    /**
     * Find the Ace editor instance for a given question container.
     *
     * @param {HTMLElement} questionDiv The question container element.
     * @return {Object|null} The Ace editor instance, or null.
     */
    function findAceEditor(questionDiv) {
        var aceEl = questionDiv.querySelector('.ace_editor');
        if (!aceEl || !aceEl.id) {
            return null;
        }
        if (typeof ace !== 'undefined' && ace.edit) {
            try {
                return ace.edit(aceEl.id);
            } catch (e) {
                return null;
            }
        }
        return null;
    }

    /**
     * Get the student's code from the question.
     *
     * @param {HTMLElement} questionDiv The question container.
     * @return {string|null} The code, or null if not found.
     */
    function getCode(questionDiv) {
        var editor = findAceEditor(questionDiv);
        if (editor) {
            return editor.getValue();
        }
        var textarea = questionDiv.querySelector('[name$="_answer"]') ||
                       questionDiv.querySelector('textarea.coderunner-answer') ||
                       questionDiv.querySelector('textarea.edit_code');
        if (textarea) {
            return textarea.value;
        }
        return null;
    }

    /**
     * Annotation type for an Ace gutter marker, derived from the lint severity.
     */
    function annotationType() {
        return 'warning';
    }

    /**
     * Clear all CQP annotations and markers from an Ace editor, and detach
     * any document anchors / change listener created by applyAnnotations.
     *
     * @param {Object} editor Ace editor instance.
     * @param {Object|null} state State returned by applyAnnotations, or null.
     */
    function clearAnnotations(editor, state) {
        var session = editor.getSession();
        session.clearAnnotations();
        if (!state) {
            return;
        }
        if (state.onChange) {
            session.off('change', state.onChange);
        }
        state.tracked.forEach(function(t) {
            session.removeMarker(t.markerId);
            t.startAnchor.detach();
            t.endAnchor.detach();
        });
    }

    /**
     * Apply CQP violation annotations and line highlights to the Ace editor.
     *
     * Uses document anchors so markers and gutter annotations track the
     * flagged lines as the student edits the code (inserts/removes lines
     * above a violation shift the highlight with the line, instead of
     * stranding it on a fixed row).
     *
     * @param {Object} editor Ace editor instance.
     * @param {Array} messages Array of CQP-enriched lint messages.
     * @return {Object} State object for clearAnnotations.
     */
    function applyAnnotations(editor, messages) {
        var session = editor.getSession();
        var doc = session.getDocument();
        var Range = ace.require('ace/range').Range;
        var tracked = [];

        messages.forEach(function(msg) {
            var row = msg.line - 1;
            var startAnchor = doc.createAnchor(row, 0);
            var endAnchor = doc.createAnchor(row, Number.MAX_VALUE);
            // Keep the end anchor pinned to the end of the (potentially
            // growing) line rather than sliding left when text is inserted.
            endAnchor.$insertRight = true;

            var range = new Range(row, 0, row, Number.MAX_VALUE);
            range.start = startAnchor;
            range.end = endAnchor;

            var cssClass = HIGHLIGHT_CLASSES[msg.type] || 'cqp-highlight-info';
            var markerId = session.addMarker(range, cssClass, 'fullLine', false);

            tracked.push({
                msg: msg,
                startAnchor: startAnchor,
                endAnchor: endAnchor,
                markerId: markerId
            });
        });

        var refreshAnnotations = function() {
            var seen = {};
            var annotations = [];
            tracked.forEach(function(t) {
                var row = t.startAnchor.row;
                // Collapse duplicates on the same row so the gutter tooltip
                // shows one merged entry when two issues end up on one line
                // after edits.
                var key = row + '|' + annotationType(t.msg.type);
                var text = '• CQP ' + t.msg.cqp_number + ': ' + t.msg.cqp_name +
                           ' (' + t.msg.symbol + ')\n  ' +
                           t.msg.message;
                if (seen[key] !== undefined) {
                    annotations[seen[key]].text += '\n\n' + text;
                    return;
                }
                seen[key] = annotations.length;
                annotations.push({
                    row: row,
                    column: 0,
                    text: text,
                    type: annotationType(t.msg.type)
                });
            });
            session.setAnnotations(annotations);
        };

        refreshAnnotations();

        var onChange = function() {
            // Defer one tick so Ace anchor positions settle before we read them.
            setTimeout(function() {
                refreshAnnotations();
                session._signal('changeBackMarker');
            }, 0);
        };
        session.on('change', onChange);

        return {tracked: tracked, onChange: onChange};
    }

    /**
     * Build the results panel HTML to show below the editor.
     *
     * @param {Object} data The analysis result from the web service.
     * @return {string} HTML string.
     */
    function buildResultsPanel(data) {
        var html = '<div class="cqp-results-panel">';

        html += '<details open>';

        // Header.
        html += '<summary class="cqp-results-header">';
        html += '<span class="cqp-results-title">Code Quality Report</span>';
        html += '<span class="cqp-issue-count">' + data.total_issues + ' issue' +
                (data.total_issues !== 1 ? 's' : '') + ' found</span>';
        html += '</summary>';

        if (data.total_issues === 0) {
            html += '<div class="cqp-clean">No issues found. Well done!</div>';
            html += '</details></div>';
            return html;
        }

        // Principle summary badges (also serve as filter toggles via initPanelFilter).
        html += '<div class="cqp-principle-summary">';
        data.principles.forEach(function(p) {
            html += '<span class="cqp-principle-badge cqp-principle-' + p.number + '" ' +
                    'data-cqp-number="' + p.number + '" ' +
                    'title="' + escapeAttr(p.short) + '">' +
                    'CQP ' + p.number + ': ' + escapeHtml(p.name) +
                    ' <span class="cqp-badge-count">(' + p.count + ')</span></span>';
        });
        html += '</div>';

        // Message groups by principle.
        data.principles.forEach(function(group) {
            html += '<div class="cqp-group" data-cqp-number="' + group.number + '">';
            html += '<div class="cqp-group-header cqp-principle-' + group.number + '-header">';
            html += '<strong>CQP ' + group.number + ': ' + escapeHtml(group.name) + '</strong>';
            html += '</div>';
            html += '<div class="cqp-group-guideline">' + escapeHtml(group.guideline) + '</div>';
            html += '<table class="table table-sm cqp-messages-table"><tbody>';
            group.messages.forEach(function(msg) {
                var rowClass = HIGHLIGHT_CLASSES[msg.type]
                    ? HIGHLIGHT_CLASSES[msg.type].replace('cqp-highlight-', 'cqp-row-')
                    : '';
                html += '<tr class="' + rowClass + '">';
                html += '<td class="cqp-line-col"><code>L' + msg.line + '</code></td>';
                html += '<td class="cqp-msg-col">' + escapeHtml(msg.message) +
                        ' <span class="cqp-symbol text-muted">(' + escapeHtml(msg.symbol) + ')</span></td>';
                html += '</tr>';
            });
            html += '</tbody></table>';
            html += '</div>';
        });

        html += '</details></div>';
        return html;
    }

    /**
     * Escape HTML special characters.
     */
    function escapeHtml(text) {
        var div = document.createElement('div');
        div.appendChild(document.createTextNode(text));
        return div.innerHTML;
    }

    /**
     * Escape for HTML attribute values.
     */
    function escapeAttr(text) {
        return text.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    }

    /**
     * Find a question container by slot number.
     *
     * @param {number}  slot          Quiz slot number.
     * @param {boolean} allowFallback True only when exactly one slot is configured
     *                                (qbank single-question preview). When multiple
     *                                slots are configured, the fallback must be
     *                                suppressed: in a sequential quiz the DOM only
     *                                contains the current page's question, so the
     *                                singleton fallback would return the wrong div
     *                                for every off-page slot and attach buttons
     *                                with the wrong questionid.
     */
    function findQuestionDiv(slot, allowFallback) {
        var selectors = [
            '#question-' + slot,
            '[id*="question-"][id$="-' + slot + '"]',
            '[data-slot="' + slot + '"]'
        ];
        for (var i = 0; i < selectors.length; i++) {
            var el = document.querySelector(selectors[i]);
            if (el) {
                return el;
            }
        }
        // Fallback for qbank preview pages where only one question is on the page.
        if (allowFallback) {
            var all = document.querySelectorAll('.que.coderunner');
            if (all.length === 1) { return all[0]; }
        }
        return null;
    }

    /**
     * Find the element we should insert our controls after — the answer
     * container wrapping the Ace editor. We insert OUTSIDE it to avoid
     * triggering Ace's auto-resize loop.
     */
    function findAnswerContainer(questionDiv) {
        var answerContainer = questionDiv.querySelector('.answer') ||
                              questionDiv.querySelector('.qtype_coderunner_answer');
        if (!answerContainer) {
            var aceEl = questionDiv.querySelector('.ace_editor');
            if (!aceEl) {
                return null;
            }
            answerContainer = aceEl.parentNode;
        }
        if (!answerContainer || !answerContainer.parentNode) {
            return null;
        }
        return answerContainer;
    }

    /**
     * Get (or create) the per-question wrapper that holds the lint controls.
     * Ensures we don't double-attach if init() fires twice.
     */
    function getOrCreateWrapper(questionDiv) {
        var existing = questionDiv.querySelector('.cqp-lint-wrapper');
        if (existing) {
            return existing;
        }
        var answerContainer = findAnswerContainer(questionDiv);
        if (!answerContainer) {
            return null;
        }
        var wrapper = document.createElement('div');
        wrapper.className = 'cqp-lint-wrapper';
        answerContainer.parentNode.insertBefore(wrapper, answerContainer.nextSibling);
        return wrapper;
    }

    /**
     * Build a lint event summary from principles for the DB JSON column.
     *
     * @param {Array} principles Array with {number, count} or {n, count} objects.
     * @return {Object} Summary object {principles: [{n, count}]}.
     */
    function buildSummary(principles, messages) {
        return {
            principles: (principles || []).map(function(p) {
                return {
                    n: p.number !== undefined ? p.number : p.n,
                    name: p.name || '',
                    count: p.count
                };
            }),
            violations: (messages || []).map(function(m) {
                return {
                    code: m.code || m.symbol || '',
                    symbol: m.symbol || '',
                    line: m.line || 0,
                    cqp: m.cqp_number !== undefined ? m.cqp_number : (m.cqp || 0)
                };
            })
        };
    }

    /**
     * Record a lint event via Moodle AJAX (stays on page — for the CQP button).
     *
     * @param {Object} slotInfo   {slot, questionid}
     * @param {number} issuecount Total issues found.
     * @param {Array}  principles Principle objects with number/count.
     * @param {Array}  messages   Per-violation messages (code, symbol, line, cqp_number).
     * @param {string} eventtype  'cqp'
     */
    function recordLintEvent(slotInfo, issuecount, principles, messages, eventtype) {
        var urlParams = new URLSearchParams(window.location.search);
        var attemptId = parseInt(urlParams.get('attempt') || '0', 10);

        Ajax.call([{
            methodname: 'local_coderunner_cqp_linter_record_lint_event',
            args: {
                questionid:  slotInfo.questionid,
                attemptid:   attemptId,
                slot:        slotInfo.slot,
                issuecount:  issuecount,
                resultsjson: JSON.stringify(buildSummary(principles, messages)),
                eventtype:   eventtype || 'cqp'
            }
        }])[0].catch(function() {
            // Logging failure is non-fatal — never disrupt the student.
        });
    }

    /**
     * Record a lint event using fetch+keepalive so it survives page navigation.
     *
     * Used for CodeRunner's Check and Precheck buttons which cause a full page
     * reload. The keepalive flag tells the browser to send the request even if
     * the page is navigating away.
     *
     * @param {Object} slotInfo   {slot, questionid}
     * @param {number} issuecount Total issues from the last CQP check (0 if none yet).
     * @param {Array}  principles Principle objects from the last CQP check.
     * @param {Array}  messages   Per-violation messages from the last CQP check.
     * @param {string} eventtype  'check' or 'precheck'
     */
    function recordLintEventKeepalive(slotInfo, issuecount, principles, messages, eventtype) {
        var urlParams = new URLSearchParams(window.location.search);
        var attemptId = parseInt(urlParams.get('attempt') || '0', 10);

        var cfg = (window.M && window.M.cfg) ? window.M.cfg : {};
        var sesskey = cfg.sesskey || '';
        var wwwroot  = cfg.wwwroot || '';

        var body = JSON.stringify([{
            index: 0,
            methodname: 'local_coderunner_cqp_linter_record_lint_event',
            args: {
                questionid:  slotInfo.questionid,
                attemptid:   attemptId,
                slot:        slotInfo.slot,
                issuecount:  issuecount,
                resultsjson: JSON.stringify(buildSummary(principles, messages)),
                eventtype:   eventtype
            }
        }]);

        try {
            fetch(wwwroot + '/lib/ajax/service.php?sesskey=' + encodeURIComponent(sesskey), {
                method:    'POST',
                headers:   {'Content-Type': 'application/json'},
                body:      body,
                keepalive: true
            });
        } catch (e) {
            // Non-fatal: research logging must never impact the student's flow.
        }
    }

    /**
     * Attach click listeners to CodeRunner's own Check and Precheck buttons.
     *
     * When either is clicked we fire a keepalive lint event (it survives the
     * ensuing page reload) carrying the last known lint state so researchers
     * can see the CQP violations the student had at the moment they ran tests.
     *
     * Buttons are identified by the Moodle question-field naming convention:
     *   Check    → name ends with "-submit"
     *   Precheck → name ends with "-precheck"
     *
     * @param {HTMLElement} questionDiv  The .que.coderunner container.
     * @param {Object}      slotInfo     {slot, questionid}
     * @param {Function}    getLastResult Returns {issuecount, principles} from last CQP check.
     */
    function attachCoderunnerListeners(questionDiv, slotInfo, getLastResult) {
        var checkSel    = 'input[type="submit"][name$="-submit"], button[type="submit"][name$="-submit"]';
        var precheckSel = 'input[type="submit"][name$="-precheck"], button[type="submit"][name$="-precheck"]';

        var checkBtn    = questionDiv.querySelector(checkSel);
        var precheckBtn = questionDiv.querySelector(precheckSel);

        if (checkBtn && !checkBtn.dataset.cqpListened) {
            checkBtn.dataset.cqpListened = '1';
            checkBtn.addEventListener('click', function() {
                var r = getLastResult();
                recordLintEventKeepalive(slotInfo, r.issuecount, r.principles, r.messages, 'check');
            });
        }

        if (precheckBtn && !precheckBtn.dataset.cqpListened) {
            precheckBtn.dataset.cqpListened = '1';
            precheckBtn.addEventListener('click', function() {
                var r = getLastResult();
                recordLintEventKeepalive(slotInfo, r.issuecount, r.principles, r.messages, 'precheck');
            });
        }
    }

    /**
     * Attach the "Check Code Quality" button to a question container.
     *
     * @param {HTMLElement} questionDiv
     * @param {HTMLElement} wrapper
     * @param {Object}      slotInfo {slot, questionid}
     */
    function attachCheckButton(questionDiv, wrapper, slotInfo) {
        if (wrapper.querySelector('.cqp-lint-btn')) {
            return;
        }

        var btn = document.createElement('button');
        btn.type = 'button';
        btn.className = 'btn btn-outline-primary btn-sm cqp-lint-btn';
        btn.textContent = 'Check Code Quality';
        btn.title = 'Analyse your code against the Code Quality Principles.';

        var resultsDiv = document.createElement('div');
        resultsDiv.className = 'cqp-results-container';
        resultsDiv.style.display = 'none';

        // Separate container for the AI feedback section (filled lazily).
        var aiDiv = document.createElement('div');
        aiDiv.className = 'cqp-ai-container';
        aiDiv.style.display = 'none';

        var currentState = null;

        // Tracks the most recent lint result so Check/Precheck listeners can
        // include it in their keepalive event even after a page reload.
        var lastLintResult = {issuecount: 0, principles: [], messages: []};

        btn.addEventListener('click', function() {
            var code = getCode(questionDiv);
            if (!code || !code.trim()) {
                resultsDiv.innerHTML = '<div class="alert alert-info" style="margin-top:0.5rem;">' +
                    'Please write some code before checking quality.</div>';
                resultsDiv.style.display = '';
                return;
            }

            // Disable button during request.
            btn.disabled = true;
            btn.textContent = 'Checking…';

            var editor = findAceEditor(questionDiv);
            if (editor) {
                clearAnnotations(editor, currentState);
                currentState = null;
            }

            Ajax.call([{
                methodname: 'local_coderunner_cqp_linter_run_lint',
                args: {
                    questionid: slotInfo.questionid,
                    code:       code
                }
            }])[0].then(function(jsonStr) {
                var data;
                try {
                    data = JSON.parse(jsonStr);
                } catch (e) {
                    data = null;
                }

                if (!data || !data.success) {
                    var errMsg = (data && data.error) ? data.error : 'Lint check failed. Please try again.';
                    resultsDiv.innerHTML = '<div class="alert alert-warning" style="margin-top:0.5rem;">' +
                        escapeHtml(errMsg) + '</div>';
                    resultsDiv.style.display = '';
                    btn.disabled = false;
                    btn.textContent = 'Check Code Quality';
                    return;
                }

                if (editor && data.messages.length > 0) {
                    currentState = applyAnnotations(editor, data.messages);
                }

                resultsDiv.innerHTML = buildResultsPanel(data);
                resultsDiv.style.display = '';
                initPanelFilter(resultsDiv);

                // Update the cached result so Check/Precheck listeners can use it.
                lastLintResult = {
                    issuecount: data.total_issues,
                    principles: data.principles,
                    messages: data.messages
                };

                recordLintEvent(slotInfo, data.total_issues, data.principles, data.messages, 'cqp');

                btn.disabled = false;
                btn.textContent = 'Check Code Quality';

                // Kick off AI analysis (separate, clearly-labelled section).
                if (slotInfo.ai) {
                    runAiAnalysis(slotInfo, code, aiDiv);
                }

            }).catch(function() {
                resultsDiv.innerHTML = '<div class="alert alert-warning" style="margin-top:0.5rem;">' +
                    'Could not reach the lint service. Please try again.</div>';
                resultsDiv.style.display = '';
                btn.disabled = false;
                btn.textContent = 'Check Code Quality';
            });
        });

        wrapper.appendChild(btn);
        wrapper.appendChild(resultsDiv);
        wrapper.appendChild(aiDiv);

        // Attach keepalive listeners to CodeRunner's own Check/Precheck buttons.
        attachCoderunnerListeners(questionDiv, slotInfo, function() { return lastLintResult; });
    }

    /**
     * Request AI analysis and render it into the given container as a separate,
     * clearly-labelled "experimental" section. Failures degrade quietly.
     *
     * @param {Object}      slotInfo  {slot, questionid}
     * @param {string}      code      The student code to analyse.
     * @param {HTMLElement} container The .cqp-ai-container element.
     */
    function runAiAnalysis(slotInfo, code, container) {
        container.innerHTML = '<div class="cqp-ai-panel"><div class="cqp-ai-header">' +
            escapeHtml(STR.aiTitle) + '</div><div class="cqp-ai-loading">' +
            escapeHtml(STR.aiLoading) + '</div></div>';
        container.style.display = '';

        Ajax.call([{
            methodname: 'local_coderunner_cqp_linter_run_ai_lint',
            args: {questionid: slotInfo.questionid, code: code}
        }])[0].then(function(jsonStr) {
            var data;
            try {
                data = JSON.parse(jsonStr);
            } catch (e) {
                data = null;
            }
            container.innerHTML = buildAiPanel(data);
            container.style.display = '';
            // Record the AI interaction for research (separate eventtype).
            if (data && data.success) {
                recordLintEvent(slotInfo, data.total_issues, data.principles, data.messages, 'ai');
            }
            return data;
        }).catch(function() {
            container.innerHTML = buildAiPanel(null);
            container.style.display = '';
        });
    }

    /**
     * Build the HTML for the separate AI feedback section.
     *
     * @param {Object|null} data Payload from run_ai_lint, or null on failure.
     * @return {string} HTML.
     */
    function buildAiPanel(data) {
        var html = '<div class="cqp-ai-panel"><details open>';
        html += '<summary class="cqp-ai-header">' +
                '<span class="cqp-ai-title">' + escapeHtml(STR.aiTitle) + '</span>' +
                '<span class="cqp-ai-badge">' + escapeHtml(STR.aiSource) + '</span></summary>';

        if (!data || !data.success) {
            html += '<div class="cqp-ai-error">' + escapeHtml(STR.aiError) + '</div>';
            html += '</details></div>';
            return html;
        }

        html += '<div class="cqp-ai-disclaimer">' + escapeHtml(STR.aiDisclaimer) + '</div>';

        if (!data.total_issues) {
            html += '<div class="cqp-clean">' + escapeHtml(STR.aiClean) + '</div>';
            html += '</details></div>';
            return html;
        }

        data.principles.forEach(function(group) {
            html += '<div class="cqp-group" data-cqp-number="' + group.number + '">';
            html += '<div class="cqp-group-header cqp-principle-' + group.number + '-header">';
            html += '<strong>CQP ' + group.number + ': ' + escapeHtml(group.name) + '</strong></div>';
            html += '<div class="cqp-group-guideline">' + escapeHtml(group.guideline) + '</div>';
            html += '<table class="table table-sm cqp-messages-table"><tbody>';
            group.messages.forEach(function(msg) {
                html += '<tr class="cqp-ai-row">';
                html += '<td class="cqp-line-col"><code>L' + msg.line + '</code></td>';
                var body = '';
                if (msg.title) {
                    body += '<strong>' + escapeHtml(msg.title) + '</strong> ';
                }
                body += escapeHtml(msg.message) +
                        ' <span class="cqp-symbol cqp-ai-tag">' + escapeHtml(STR.aiSource) + '</span>';
                html += '<td class="cqp-msg-col">' + body + '</td>';
                html += '</tr>';
            });
            html += '</tbody></table></div>';
        });

        html += '</details></div>';
        return html;
    }

    /**
     * Make principle badges in a panel act as filter toggles.
     *
     * Clicking a badge hides all groups for other principles (and dims their
     * badges). Clicking again deselects it. Works on both the JS-generated
     * results panel and the server-rendered review panel.
     *
     * @param {HTMLElement} panel Container element with .cqp-principle-badge
     *                            and .cqp-group[data-cqp-number] children.
     */
    function initPanelFilter(panel) {
        var badges = panel.querySelectorAll('.cqp-principle-badge[data-cqp-number]');
        if (badges.length < 2) {
            return; // Nothing useful to filter with a single principle.
        }

        var activeFilters = [];

        function updateFilter() {
            panel.querySelectorAll('.cqp-group[data-cqp-number]').forEach(function(group) {
                var num = parseInt(group.dataset.cqpNumber, 10);
                group.style.display = (activeFilters.length === 0 || activeFilters.indexOf(num) !== -1)
                    ? '' : 'none';
            });
            badges.forEach(function(b) {
                var num = parseInt(b.dataset.cqpNumber, 10);
                var selected = activeFilters.length === 0 || activeFilters.indexOf(num) !== -1;
                if (selected) {
                    b.classList.remove('cqp-badge-dimmed');
                } else {
                    b.classList.add('cqp-badge-dimmed');
                }
            });
        }

        badges.forEach(function(badge) {
            badge.addEventListener('click', function() {
                var num = parseInt(badge.dataset.cqpNumber, 10);
                var idx = activeFilters.indexOf(num);
                if (idx !== -1) {
                    activeFilters.splice(idx, 1);
                } else {
                    activeFilters.push(num);
                }
                updateFilter();
            });
        });
    }

    /**
     * Apply Ace editor gutter annotations and line highlights from a
     * server-rendered lint panel (review page).
     *
     * The panel's .pylint-message-row elements carry data-line and severity
     * CSS classes that map directly to the same highlight classes used on
     * the attempt page.
     *
     * @param {HTMLElement} questionDiv The .que.coderunner container.
     * @param {HTMLElement} panel       The .coderunner-pylint-panel element.
     */
    function applyReviewAnnotations(questionDiv, panel) {
        var editor = findAceEditor(questionDiv);
        if (!editor) {
            return;
        }

        var Range;
        try {
            Range = ace.require('ace/range').Range;
        } catch (e) {
            return;
        }

        var session = editor.getSession();
        var annotations = [];

        panel.querySelectorAll('.pylint-message-row').forEach(function(row) {
            var lineNum = parseInt(row.dataset.line || '', 10);
            if (isNaN(lineNum) || lineNum < 1) {
                return;
            }
            var aceRow = lineNum - 1;

            // Build tooltip text from the group header and message cell.
            var group = row.closest ? row.closest('.cqp-group') : null;
            var headerEl = group ? group.querySelector('.cqp-group-header strong') : null;
            var cqpLabel = headerEl ? headerEl.textContent.trim() : 'CQP issue';
            var msgCell = row.querySelector('.pylint-msg-col');
            var msgText = msgCell ? msgCell.textContent.trim() : '';
            var annotText = '• ' + cqpLabel + '\n  ' + msgText;

            // Merge multiple issues on the same line into one annotation entry.
            var existing = null;
            for (var i = 0; i < annotations.length; i++) {
                if (annotations[i].row === aceRow) { existing = annotations[i]; break; }
            }
            if (existing) {
                existing.text += '\n\n' + annotText;
            } else {
                annotations.push({row: aceRow, column: 0, text: annotText, type: 'warning'});
            }

            // Map pylint-* severity class to cqp-highlight-* marker class.
            var cssClass = 'cqp-highlight-convention';
            row.className.split(/\s+/).forEach(function(cls) {
                if (cls !== 'pylint-message-row' && cls.indexOf('pylint-') === 0) {
                    cssClass = cls.replace('pylint-', 'cqp-highlight-');
                }
            });
            session.addMarker(new Range(aceRow, 0, aceRow, Number.MAX_VALUE), cssClass, 'fullLine', false);
        });

        if (annotations.length > 0) {
            session.setAnnotations(annotations);
        }
    }

    return {
        /**
         * Initialise the CQP linter for the specific CodeRunner questions
         * passed in by the PHP side. Only questions whose teacher has
         * explicitly enabled linting should appear in the slots list.
         *
         * On review pages, server-rendered panels are already in the DOM:
         * we apply Ace editor highlights from them and make badges filterable.
         * On attempt/preview pages, we inject the interactive CQP button.
         *
         * @param {Object} config {slots: [{slot, questionid}]}
         */
        init: function(config) {
            var slots = (config && config.slots) || [];
            if (slots.length === 0) {
                return;
            }

            var doInit = function() {
                var singleSlot = slots.length === 1;
                slots.forEach(function(slotInfo) {
                    var questionDiv = findQuestionDiv(slotInfo.slot, singleSlot);
                    if (!questionDiv) {
                        return;
                    }

                    // Review page: server-rendered panel already present in DOM.
                    var existingPanel = questionDiv.querySelector('.coderunner-pylint-panel');
                    if (existingPanel) {
                        applyReviewAnnotations(questionDiv, existingPanel);
                        initPanelFilter(existingPanel);
                        return;
                    }

                    // Attempt/preview page: inject the interactive button.
                    var wrapper = getOrCreateWrapper(questionDiv);
                    if (!wrapper) {
                        return;
                    }
                    attachCheckButton(questionDiv, wrapper, slotInfo);
                });
            };

            // Delay to let Ace editors and injected panels settle.
            if (document.readyState === 'loading') {
                document.addEventListener('DOMContentLoaded', function() {
                    setTimeout(doInit, 500);
                });
            } else {
                setTimeout(doInit, 500);
            }
        }
    };
});
